apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-testing-service
spec:
  scaleTargetRef:
    kind: Deployment
    name: test-service-deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
