apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: testing-service
  labels:
    version: 0.0.1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: frontend
        env: dev
    spec:
      containers:
        - name: test-ser
          image: "docker.io/jagadesh1982/testing-service"
          ports:
           - containerPort: 9876
