apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /loddisk2/share
    server: 10.131.175.138
  persistentVolumeReclaimPolicy: Recycle

