apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  volumes:
     - name: my-nfs
       persistentVolumeClaim:
         claimName: my-claim
  containers:
    - name: test-ser
      image: docker.io/jagadesh1982/testing-service
      ports:
      - containerPort: 9876
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
      volumeMounts:
          - mountPath: /var/www/html
            name: my-nfs
  nodeSelector:
    label: node1

