apiVersion: v1
kind: Pod
metadata:
  name: testing-service
  labels:
    env: dev   
spec:
  containers:
    - name: test-ser
      image: docker.io/jagadesh1982/testing-service
      ports:
      - containerPort: 9876

