apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
   - image: mysql:latest
     name:  "mysql"
     ports:
       - containerPort: 3306
     volumeMounts:
       - name: apikeyvol
         mountPath: "/tmp/apikey"
         readOnly: true
  volumes:
  - name: apikeyvol
    secret:
      secretName: apikey

