apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
    - name: test-ser
      image: docker.io/jagadesh1982/testing-service
      ports:
      - containerPort: 9876
    - name: shell
      image: centos:7
      command:
        - "/usr/bin/bash"
        - "-c"
        - "sleep 10000"  
