apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
  - name: testing
    image: docker.io/jagadesh1982/testing-service
    volumeMounts:
      - mountPath: /etc/sidekiq/config
        name: testing-service-staging
  volumes:
    - name: testing-service-staging
      configMap:
         name: testing-service-staging
         items:
          - key: config
            path:  testing-stage.yml
