apiVersion: v1
kind: Pod
metadata:
  name: "mysql"
  labels:
   name: "lbl-k8s-mysql"
spec:
  containers:
   - image: docker.io/jagadesh1982/testing-service 
     name:  "testing"
     imagePullPolicy: IfNotPresent
     ports:
      - containerPort: 3306
     volumeMounts:
       - mountPath: /data-mount
         name: data
  volumes:
    - name: data
      emptyDir: 
        medium: Memory 

