apiVersion: v1
kind: Pod
metadata:
  name: "mysql"
  labels:
   name: "lbl-k8s-mysql"
spec:
  containers:
   - image: mysql:latest
     name:  "mysql"
     imagePullPolicy: IfNotPresent
     ports:
      - containerPort: 3306
     volumeMounts:
       - mountPath: /data-mount
         name: data
  volumes:
    - name: data
      emptyDir: {}

