apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
    - name: test-ser
      image: docker.io/jagadesh1982/testing-service
      ports:
      - containerPort: 9876
      lifecycle: 
          postStart:  
            exec:
              command: ["/bin/sh", "-c", "touch /tmp/hello"]
          preStop: 
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the preSop handler > /tmp/hello"]
