apiVersion: v1
kind: Pod
metadata:
  name: "mysql"
  labels:
   name: "lbl-k8s-mysql"
spec:
  containers:
   - image: mysql:latest
     name:  "mysql"
     ports:
      - containerPort: 3306
     volumeMounts:
       - mountPath: /var/www/html
         name: my-nfs
  volumes:
    - name: my-nfs
      persistentVolumeClaim:
        claimName: my-claim-1

