apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9876
      nodePort: 30036
      protocol: TCP 
  selector:
    app: testingService-service
