apiVersion: v1
kind: Service
metadata:
  name: testing-service
  labels:
    app: testings-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: testing-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testing-service
  labels:
    app: testing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testing-service
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: testing-service
  template:
    metadata:
      labels:
        app: testing-service
        version: "1.0"
    spec:
      containers:
      - name: test-service
        image: docker.io/jagadesh1982/testing-service
        ports:
        - name: http
          containerPort: 9876
        env:
        - name: VERSION
          value: "1.0"
