apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
  - name: testing
    image: docker.io/jagadesh1982/testing-service
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
