apiVersion: v1
kind: Pod
metadata:
  name: "testing-service"
  labels:
   name: "testingService"
spec:
  containers:
   - image: docker.io/jagadesh1982/testing-service 
     name:  "testing"
     imagePullPolicy: IfNotPresent
     ports:
       - containerPort: 9876
     volumeMounts:
       - name: apikeyvol
         mountPath: "/tmp/apikey"
         readOnly: true
  volumes:
   - name: apikeyvol
     secret:
       secretName: apikey


